[package]
name = "simple_rate_calc"
version = "0.9.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.27.2"
egui = "0.27.2"
native-dialog = "0.7.0"
serde = "1.0.198"
serde_json = "1.0.116"
